### ISSUE TITLE
[Feature request] Per-package, per-atom (and per-category?) configuration

### ISSUE THREAD

**Issue by kuraga** [pkgcore/pkgcheck#533] opened 2023-01-29 12:04 UTC
Feature request: per-package, per-atom (and per-category?) configuration.

Motivation example: sometimes issues may be considered as acceptable temporarily. It would be conveniently to turn off some warnings.

**Comment by thesamesam** [comment] 2023-01-29 13:08
i think this is mostly a duplicate of https://github.com/pkgcore/pkgcheck/issues/478.

**Closed** 2023-01-29 13:10 UTC
