### ISSUE TITLE
FileNotFoundError in pkgcheck scan --commits w/ LLVM removals

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#460] opened 2022-10-07 08:59 UTC
```pytb
$ pkgcheck scan --commits  
[...]
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkgcheck/pipeline.py", line 186, in _run_checks
    if results := sorted(chain.from_iterable(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/runners.py", line 70, in run
    yield from check.feed(item)
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/git.py", line 354, in feed
    yield from self.removal_checks(list(pkg_map['D']))
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/git.py", line 260, in removal_checks
    p.keywords for p in removal_repo.match(pkg.unversioned_atom)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 232, in match
    return list(self.itermatch(atom, **kwds))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 300, in _internal_match
    for pkg in self._internal_gen_candidates(candidates, **kwargs):
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 297, in _internal_gen_candidates
    yield from sorter(pkg_filter(pkgs))
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/repository.py", line 510, in _pkg_filter
    if not pkg.is_supported:
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/klass.py", line 353, in __call__
    return self.getter(obj)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/package/base.py", line 97, in dynamic_getattr_dict
    val = functor(self)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/ebuild_src.py", line 246, in eapi
    i = fileutils.readlines_utf8(ebuild.path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/_fileutils.py", line 78, in native_readlines
    handle = open(mypath, mode, encoding=encoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp-pkgcheck-0iof3k95.repo/sys-libs/compiler-rt-sanitizers/compiler-rt-sanitizers-15.0.1.ebuild'
```

origin/master is gentoo/gentoo@7558ca0bef3f5262e9c9e133b85989beeda4fb2a
master is mgorny/gentoo@97ca77073caf2684c96bcaa13b85a089329c69c8 as found in https://github.com/mgorny/gentoo/tree/llvm-removals

**Comment by arthurzam** [comment] 2022-10-07 09:33
Reproduced using:
```
pkgcheck scan --commits 97ca770..7558ca0
```

**Comment by arthurzam** [comment] 2022-10-07 11:13
@mgorny I can't say how much this reproducer was excellent! Because of the long list of commits, and nearly each one of them was good enough to create a situation where the problem might occur, which helped a lot with finding the issue and fixing it.

While in every run (even with `-j 1`) I got failure with another package, I always got the same bad state. More explanation will be in the PR I will open now.

**Closed** 2022-10-07 12:42 UTC
Labels: bug
