### ISSUE TITLE
Hard Crash: partially staged files

### ISSUE THREAD

**Issue by ezzieyguywuf** [pkgcore/pkgcheck#318] opened 2021-04-28 20:03 UTC
While this is a reasonable expectation - in other words, `pkgcheck scan --staged` can't be expected to do anything if nothing is staged - I also think it is reasonable for pkgcheck to gracefully exit and provide a useful message.

Instead, there is some sort of `IndexError`, I think because the `git` output is used non-conditionally, and thus if there is no output things blow up.

edit:

Ok, my original report misleading. Here are the steps to reproduce:

1. Modify an ebuild
2. `git add` the change
3. Modify the *same* ebuild again
4. Try to execute `pkgcheck scan --staged`

It seems that having a partially staged partially unstaged file is what causes the error.

edit:

yikes, not only does it crash, but it also mangles the file in question with all the git merge conflict stuff.

**Comment by radhermit** [comment] 2021-05-24 07:25
I can't reproduce this with a simple test case, please attach the backtrace from the crash.

**Comment by radhermit** [comment] 2021-05-27 23:17
Closing because I can't reproduce this, feel free to reopen with more information including a full backtrace.

**Closed by radhermit** 2021-05-27 23:17 UTC
